name = "Rini"
uuid = "bcdbd595-53fa-4147-b56f-4aca9bc6494d"
authors = ["Carlos <gcarlos.rincon@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[compat]
Plots = "1.40.8"
SymPy = "2.2.0"
